## **Task 13 Solution** ##


**Question 1**
- Create a 6x6 NumPy array with random integers between 1 and 50. 
- Display the array.

In [ ]:

# importing numpy library
import numpy as np

# method 2 to generate random integer numbers
rng = np.random.default_rng()

# printing random integer numbers using random and randint
arr_6 = np.random.randint(1,50, [6, 6])

# printing the 6x6 numpy array
print("A 6x6 Numpy Array\n", arr_6)
rng.integers(1,51, size=(6, 6))




A 6x6 Numpy Array
 [[48 37 28 49  7 24]
 [19 10 40 20  5 24]
 [47 30 24  4 36 37]
 [37 37 11 17 48  1]
 [14 32 49 36 30 12]
 [30 49  9 47 12 45]]


array([[ 8, 26, 41, 30, 37, 47],
       [48, 26, 29, 40, 32, 44],
       [ 2, 24, 28, 38, 42, 25],
       [43,  3, 25, 43, 22, 29],
       [12, 18, 10, 49,  2, 36],
       [29, 19, 25,  5, 44, 28]])

**Question 2**
Extract the following from the array you created in Question 1: 
- The first two rows. 
- The last three columns. 
- All even numbers in the array.

In [130]:

# Extracting the first two rows
print("First two rows in the array\n" , arr_6[0:2])

# Extracting the last three columns
print("The last three columns in the array\n" , arr_6[:, 3:])

# Extracting all even numbers in the array
even_arrays = arr_6[arr_6%2 == 0]
print("This is the list of even numbers within the array\n", even_arrays)


First two rows in the array
 [[48 37 28 49  7 24]
 [19 10 40 20  5 24]]
The last three columns in the array
 [[49  7 24]
 [20  5 24]
 [ 4 36 37]
 [17 48  1]
 [36 30 12]
 [47 12 45]]
This is the list of even numbers within the array
 [48 28 24 10 40 20 24 30 24  4 36 48 14 32 36 30 12 30 12]


**Question 3**
 Perform the following array transformations:
- Reshape the array into a 3D (3, 2, 6) array. 
-  Flatten the reshaped array back to 1D.


In [131]:

# Reshaping the array to a 3D array
reshape_3d = arr_6.reshape(3,2,6)
print("Reshaped to 3x2x6: \n\n", reshape_3d)

#  Flatten the reshaped array back to 1D.
flattened = reshape_3d.flatten()
print("\nFlattened the reshaped array back to 1D\n", flattened)

Reshaped to 3x2x6: 

 [[[48 37 28 49  7 24]
  [19 10 40 20  5 24]]

 [[47 30 24  4 36 37]
  [37 37 11 17 48  1]]

 [[14 32 49 36 30 12]
  [30 49  9 47 12 45]]]

Flattened the reshaped array back to 1D
 [48 37 28 49  7 24 19 10 40 20  5 24 47 30 24  4 36 37 37 37 11 17 48  1
 14 32 49 36 30 12 30 49  9 47 12 45]


**Question 4**
-  Generate a 4x4 identity matrix and replace the diagonal with numbers from 10 to 40, with a step of 10.

In [133]:
# generating a 4x4 identity matrix
identity_matrix = np.eye(4)

# setting values to replace the identity matrix diagonal
diagonal_numbers = np.arange(10, 41,10)

# setting the identity diagonal numbers
np.fill_diagonal(identity_matrix, diagonal_numbers)

# displaying the matrix
print(identity_matrix)



[[10.  0.  0.  0.]
 [ 0. 20.  0.  0.]
 [ 0.  0. 30.  0.]
 [ 0.  0.  0. 40.]]


**Question 5**
- Perform matrix multiplication between: A 3x4 matrix of random integers (1-10) A 4x3 matrix of random integers (1-10)

In [ ]:
# A 3x4 matrix of random integers
matrix1 = np.random.randint(1,11, [3, 4])
print("A 3x4 matrix\n", matrix1)

# A 4x3 matrix of random integers
matrix2 = np.random.randint(1,11, [4, 3])
print("A 4x3 matrix\n", matrix2)

# Reshaping matrix2 array to a 3x4 array
reshaped_array = matrix2.reshape(3,4)
print("Reshaped to 3x4: \n\n", reshaped_array)

# multiplying the matrix
multiplied_array = matrix1 * reshaped_array

# printing output
print("This multiplies matrix1 by matrix2: \n\n", multiplied_array)


A 3x4 matrix
 [[2 5 6 3]
 [4 3 7 4]
 [8 5 6 2]]
A 4x3 matrix
 [[ 1  4  4]
 [ 4  6 10]
 [ 5  2  5]
 [ 3  2  7]]
Reshaped to 3x4: 

 [[ 1  4  4  4]
 [ 6 10  5  2]
 [ 5  3  2  7]]
This multiplies matrix1 by matrix2: 

 [[ 2 20 24 12]
 [24 30 35  8]
 [40 15 12 14]]


**Question 6**
-  Create a function that takes a 2D NumPy array as input and returns a new array where:
-  All even numbers are squared. 
- All odd numbers are replaced by -1.

In [128]:
# function to create the 2D numpy array
def array_input():
   
    print("Performing operations on 2D NumPy array")
    
    # taking number of row inputs
    array_rows= np.array(int(input("Enter number of rows for the 2D array: ")))

    # taking number of columns input
    array_cols= np.array(int(input("Enter number of columns for the 2D array: ")))

    # shaping the 2D array and putting the range of numbers
    array_2d = np.arange(array_cols * array_rows).reshape(array_rows, array_cols)

    # Ensuring all even numbers are squared and all odd numbers are replaced by -1.
    new_array = np.where(array_2d % 2 == 0, array_2d**2, -1)
    
    # returning the 2D array
    return new_array

# printing the function
print(array_input())



Performing operations on 2D NumPy array
[[  0  -1   4  -1  16  -1]
 [ 36  -1  64  -1 100  -1]
 [144  -1 196  -1 256  -1]
 [324  -1 400  -1 484  -1]]
