## **Task 13 Solution** ##


**Question 1**
- Create a 6x6 NumPy array with random integers between 1 and 50. 
- Display the array.

In [96]:


import numpy as np
rng = np.random.default_rng()

arr_6 = np.random.randint(1,50, [6, 6])

print("A 6x6 Numpy Array\n", arr_6)

rng.integers(1,51, size=(6, 6))




A 6x6 Numpy Array
 [[ 4 42 35 16 41 23]
 [45  8  6 45  9 17]
 [32  9 17  1 19 38]
 [ 5 29 14 38 49  1]
 [46 46  4 22 24 10]
 [26 25 15  6 28 47]]


array([[50,  4, 46, 39, 16,  7],
       [23, 38, 32, 33, 22, 33],
       [33, 12, 26, 39,  9, 31],
       [28, 40, 32, 28, 22, 40],
       [25,  2, 37,  1,  1, 42],
       [37, 37, 39, 21,  1, 47]])

**Question 2**
Extract the following from the array you created in Question 1: 
- The first two rows. 
- The last three columns. 
- All even numbers in the array.

In [115]:

# Extracting the first two rows
print("First two rows in the array\n" , arr_6[0:2])

# Extracting the last three columns
print("The last three columns in the array\n" , arr_6[:, 3:])

# Extracting all even numbers in the array
even_arrays = arr_6[arr_6%2 == 0]
print("This is the list of even numbers within the array\n", even_arrays)


First two rows in the array
 [[ 4 42 35 16 41 23]
 [45  8  6 45  9 17]]
The last three columns in the array
 [[16 41 23]
 [45  9 17]
 [ 1 19 38]
 [38 49  1]
 [22 24 10]
 [ 6 28 47]]
This is the list of even numbers within the array
 [ 4 42 16  8  6 32 38 14 38 46 46  4 22 24 10 26  6 28]


**Question 3**
 Perform the following array transformations:
- Reshape the array into a 3D (3, 2, 6) array. 
-  Flatten the reshaped array back to 1D.


In [73]:

# Reshaping the array to a 3D array
reshape_3d = arr_6.reshape(3,2,6)
print("Reshaped to 3x2x6: \n\n", reshape_3d)

#  Flatten the reshaped array back to 1D.
flattened = reshape_3d.flatten()
print("\nFlattened the reshaped array back to 1D\n", flattened)

Reshaped to 3x2x6: 

 [[[ 7 27 18 40  1 16]
  [31  2  5  5  4  1]]

 [[45 48 14 32 33 44]
  [ 9 27 35  2 28  6]]

 [[31 24 47  6 15 41]
  [ 5 17 36 39 19 23]]]

Flattened the reshaped array back to 1D
 [ 7 27 18 40  1 16 31  2  5  5  4  1 45 48 14 32 33 44  9 27 35  2 28  6
 31 24 47  6 15 41  5 17 36 39 19 23]


**Question 4**
-  Generate a 4x4 identity matrix and replace the diagonal with numbers from 10 to 40, with a step of 10.

In [ ]:
# generating an identity maytrix

identity_matrix = np.eye(4)

# setting values to replace the identity matrix diagonal
diagonal_numbers = np.arange(10, 41,10)

np.fill_diagonal(identity_matrix, diagonal_numbers)

print(identity_matrix)



**Question 5**
- Perform matrix multiplication between: A 3x4 matrix of random integers (1-10) A 4x3 matrix of random integers (1-10)

In [109]:
# A 3x4 matrix of random integers
matrix1 = np.random.randint(1,11, [3, 4])
print("A 3x4 matrix\n", matrix1)

# A 4x3 matrix of random integers
matrix2 = np.random.randint(1,11, [4, 3])
print("A 4x3 matrix\n", matrix2)

# Reshaping the array to a 3D array
reshaped_array = matrix2.reshape(3,4)
print("Reshaped to 3x4: \n\n", reshaped_array)

multiplied_array = matrix1 * reshaped_array

print("This multiplies matrix1 by matrix2: \n\n", multiplied_array)


A 3x4 matrix
 [[2 5 6 3]
 [4 3 7 4]
 [8 5 6 2]]
A 4x3 matrix
 [[ 1  4  4]
 [ 4  6 10]
 [ 5  2  5]
 [ 3  2  7]]
Reshaped to 3x4: 

 [[ 1  4  4  4]
 [ 6 10  5  2]
 [ 5  3  2  7]]
This multiplies matrix1 by matrix2: 

 [[ 2 20 24 12]
 [24 30 35  8]
 [40 15 12 14]]


**Question 6**
-  Create a function that takes a 2D NumPy array as input and returns a new array where:
-  All even numbers are squared. 
- All odd numbers are replaced by -1.

In [ ]:
def array_input():
   
    print("Performing operations on 2D NumPy array")
    
    array_rows= np.array(int(input("Enter number of rows for the 2D array: ")))
    array_cols= np.array(int(input("Enter number of columns for the 2D array: ")))

    array_2d = np.arange(array_cols * array_rows).reshape(array_rows, array_cols)

    new_array = np.where(array_2d % 2 == 0, array_2d**2, -1)
    
    return new_array


print(array_input())



Performing operations on 2D NumPy array
[[  0  -1   4  -1]
 [ 16  -1  36  -1]
 [ 64  -1 100  -1]]
