## **Class Task 2** ##

**Given the following matrices**

``` 
A = 2  -1  3
    0   4  1
```


``` 
B = 1    2
   -2    0
    5   -3
```



**A. Identify the number of rows and columns in each matrix.**

- A = (2 rows, 3 columns) # 2 x 3 matrix
- B = (3 rows, 2 columns) # 3 X 2 matrix

**B. Determine whether the matrices can be multiplied.If so, specify whether it's (AB), (BA), or both.**

- **A(2, 3) * B(3, 2)**

     The matrices A and B can be multiplied to give AB

     This is  because the number of columns in A matches the number of rows in B.


- **AB is a (2 x 2) matrix**
    ```
      AB = 19  -5
            3  -3
    ```  


- **B(3, 2) * A(2, 3)**

    The matrices B and A can be multiplied to give BA

    This is  because the number of columns in B matches the number of rows in A


- **BA is a (3 x 3) matrix**
    ```
      BA = 2   7   3
          -4   2   -6
          10  -17  12
    ```   

- **Conclusion**

   Both AB and  BA can be multiplied   

**C. If the multiplication is defined, compute the resulting matrix using numpy**

In [2]:
# computing the resulting matrix using numpy

import numpy as np

a= np.array([[2, -1, 3],[0, 4, 1 ]])
b= np.array([[1, 2], [-2, 0], [5, -3]])

# multiplying matrices in numpy using standard matrix product .dot()
ab= np.dot(a,b)
ba =np.dot(b,a)


print(f"The result of  A(2, 3) * B(3, 2) is:\n {ab}\n AB (2,2) matrix")
print(f"The result of  B(3, 2) * B(2, 3) is:\n {ba}\n AB (3,3) matrix")

The result of  A(2, 3) * B(3, 2) is:
 [[19 -5]
 [-3 -3]]
 AB (2,2) matrix
The result of  B(3, 2) * B(2, 3) is:
 [[  2   7   5]
 [ -4   2  -6]
 [ 10 -17  12]]
 AB (3,3) matrix
