## **Case Study: Student Performance Analysis with Linear Algebra**

## Step-by-step Analysis

## **3.1 Representing the data as a Matrix**
```
rows = students, columns = subjects
student_scores = (4 X 3) matrix 
student_scores= [
                  [80,70,90],
                  [60,85,75],
                  [95,88,92],               
                  [70,60,65]
                ]

In [2]:
# representing the data as a matrix
import numpy as np
student_scores = np.array([[80,70,90],
                           [60,85,75],
                           [95,88,92],
                           [70,60,65]])
student_scores

array([[80, 70, 90],
       [60, 85, 75],
       [95, 88, 92],
       [70, 60, 65]])

## **3.2. Computing Total Score per Student (Vector Addition)**
```
student_scores= [
                  [80,70,90],
                  [60,85,75],
                  [95,88,92],               
                  [70,60,65]
                ]
```                
- Total score for each student by summing across the row vector.

        - Total score for each student:
            student_one = (80 + 70 + 90)
                student_one = 240
            student_two = (60 + 85 + 75)
                student_two = 220
            student_three = (95 + 88 + 92)
                student_three = 275
            student_four = (70 + 60 + 65)
                student_four = 195

```
    total_score_array = [240 220 275 195]                


In [3]:
# computing total score for each student by summing across the row  using numpy.
student_scores = np.array([[80,70,90],
                           [60,85,75],
                           [95,88,92],
                           [70,60,65]])

# calculating the scores across the row for each student, 
# rows = students, columns = subjects
total_scores_array = np.sum(student_scores, axis = 1)
print("The total score array of each student is: ", total_scores_array)

The total score array of each student is:  [240 220 275 195]


## **3.3 Applying Weights (Scalar Multiplication)**

- Representing all students maths score in an array
```
    math_scores = [80, 60, 95, 70]
```
- Math is twice as important as others, `scalar m = 2`   

- Scalar multiplictaion to apply weight on the math subject:
   ```
     weighted_math_score = 2(math_scores)
     2(math_scores) => 2([80, 60, 95, 70])
                        [(2 x 80), (2 X 60), (2 X 95), (2 X 70)]
                        [160 120 190 140]

    weighted_math_score = [160  120 190 140]


In [4]:
# representing all students maths score in an array
math_scores = np.array(student_scores[:,0])

# scalar value
scalar_m = 2
weighted_math_score = scalar_m * math_scores

print("The weighted math score for each student is: ", weighted_math_score)


The weighted math score for each student is:  [160 120 190 140]


## **3.4 Average Score per Subject  (Matrix Operations)**

- Representing each subject score in an array
```
    math_scores = [80, 60, 95, 70]
    english_scores = [70, 85, 88, 60]
    science_scores = [90, 75, 92,65]
    total_students = 4
```
        math_scores_avg = sum of math_scores / total_students
                        = (80 + 60 + 95 + 70) / 4
                                        = 305 / 4
                                        = 76.25
                        math_scores_avg = 76.25                           

```
        english_scores_avg = sum of english_scores / total_students
                                = (70 + 85 + 88 + 60) / 4
                                                = 303 / 4
                                                = 75.75
                                english_scores_avg = 75.75 

```
        science_scores_avg = sum of science_scores / total_students
                                = (90 + 75 + 92 + 65) / 4
                                                = 322 / 4
                                                = 80.5
                                science_scores_avg = 80.5                          


In [5]:
# representing all students subject score in an array
math_scores = np.array(student_scores[:,0])
english_scores = np.array(student_scores[:,1])
science_scores = np.array(student_scores[:,2])

# calculating the mean of the students scores in each subject
math_scores_avg = np.mean(math_scores, axis=0)
english_scores_avg = np.mean(english_scores, axis=0)
science_scores_avg = np.mean(science_scores, axis=0)

print("The Average of all the student scores in Mathematics is: ", math_scores_avg)
print("The Average of all the student scores in English is: ", english_scores_avg)
print("The Average of all the student scores in Science is: ", science_scores_avg)

The Average of all the student scores in Mathematics is:  76.25
The Average of all the student scores in English is:  75.75
The Average of all the student scores in Science is:  80.5


## **3.5 Final Grades Using Matrix Multiplication**

- Representing each subject score in an array
```
    student_scores= [
                  [80,70,90],
                  [60,85,75],
                  [95,88,92],               
                  [70,60,65]
                ]
  student_scores(4 X 3)

```
        weight_vector = [ 40% = 0.4 = maths,
                          40% = 0.4 = english,
                          20% = 0.2 = science
                        ]
       weight_vector (3 X 1)
```
 - final_grade(4 X 1) = (student_scores X weight_vector)
                         
                          student_1_grade = [(80 X 0.4), (70 x 0.4),  (90 X 0.2)]
                          student_2_grade = [(60 X 0.4), (85 x 0.4),  (75 X 0.2)]
                          student_3_grade = [(95 X 0.4), (88 x 0.4),  (92 X 0.2)]
                          student_4_grade = [(70 X 0.4), (60 x 0.4),  (65 X 0.2)]
 - final_grade

                          student_1_grade = [32     28     18]
                          student_2_grade = [24     34     15]
                          student_3_grade = [38   35.2   18.4]
                          student_4_grade = [28     24      13]

  - Total final grade for each student:
  ```
                          student_1_final = (32 + 28 + 18)
                              student_1_final = 78

                          student_2_final = (24 + 34 + 15)
                              student_2_final = 73

                          student_3_final = (38 + 35.2 + 18.4)
                              student_3_final = 91.6
                              
                          student_4_final = (28 + 24 + 13)
                              student_4_final = 65

```
```
- Grades
    - A = 75 - 100
    - B = 65 - 74
    - C = 64 - 55
    - D = 54 - 45
    - E = 44 - 40
    - F = 39 - 0


    \begin{bmatrix}
    Students & Scores &Grades\\
    Student_1 & 78 & A\\
    Student_2 & 73 & B\\
    Student_3 & 91.6 & A\\
    Student_4 & 65 & B\\
    \end{bmatrix}                   
                         

In [6]:
# representing all subject weight vector in an array
weight_vector = [0.4, 0.4, 0.2]

student_1 = np.array(student_scores[0, :])
student_2= np.array(student_scores[1, :])
student_3 = np.array(student_scores[2, :])
student_4 = np.array(student_scores[3, :])

# calculating the sum of the students scores in each subject
student_1_final = np.sum(student_1 * weight_vector)
student_2_final= np.sum(student_2 * weight_vector)
student_3_final = np.sum(student_3 * weight_vector)
student_4_final = np.sum(student_4 * weight_vector)

# adding the final grade for each student
print("Student 1 Final Grade is: ", student_1_final ,"%")
print("Student 2 Final Grade is: ", student_2_final,"%")
print("Student 3 Final Grade is: ", student_3_final,"%")
print("Student 4 Final Grade is: ", student_4_final,"%")



Student 1 Final Grade is:  78.0 %
Student 2 Final Grade is:  73.0 %
Student 3 Final Grade is:  91.60000000000001 %
Student 4 Final Grade is:  65.0 %


## **3.6 Comparing Students (Vector Subtraction)**

- comparing two students performnances by subtracting their score vectors
  - Total final grade for each student:
  ```
                                 student 1 grade = [80,70,90],
                                  student 2 grade = [60,85,75]
                          
- Student performance comparison by subtracting their score vector:
```
                        performance_comparison = [(80 -60), (70 - 85), (90 - 75)]
                                               =  [20   -15   15]
                                             
```                                                       
                         

In [16]:
student_scores = np.array([[80,70,90],
                           [60,85,75],
                           [95,88,92],
                           [70,60,65]])
student_1 = np.array(student_scores[0, :])
student_2 = np.array(student_scores[1, :])
# Student performance comparison by subtracting their score vector:
performance_comparison = student_1 - student_2
performance_comparison
print("The difference between the performance of Students 2 and Student 1 is: ", performance_comparison,"%", "hence; student 1 performed better")

The difference between the performance of Students 2 and Student 1 is:  [ 20 -15  15] % hence; student 1 performed better


## Add-on Exercises

- Create a new 5×4 matrix of scores (5 students, 4 subjects). 
- Compute each student’s total score and the average per subject. 

```
rows = students, columns = subjects
student_scores = (5 X 4) matrix 
student_scores_2 = [
                    [90, 74, 63, 86],
                    [96, 51, 85, 97],
                    [78, 99, 99, 99],
                    [51, 66, 75, 84],
                    [82, 92, 82, 70]
                    ]
```                    

In [8]:
# a 5 x 4 matrix of scores(5 students, 4 subjects)
student_scores_2= np.random.randint(50, 100, (5, 4))
student_scores_2 = np.array([
       [90, 74, 63, 86],
       [96, 51, 85, 97],
       [78, 99, 99,82],
       [51, 66, 75, 84],
       [82, 92, 82, 70]])

                
- Total score for each student by summing across the row vector.
```
       - student_scores_2 = [
                            [90, 74, 63, 86],
                            [96, 51, 85, 97],
                            [78, 99, 99, 99],
                            [51, 66, 75, 84],
                            [82, 92, 82, 70]
                            ]

        - Total score for each student:
                student_one = (90 + 74 + 63 + 86)
                    student_one = 313
                student_two = (96 + 51 + 85 + 97)
                    student_two = 329
                student_three = (78 + 99 + 99 + 82)
                    student_three = 358
                student_four = (51 + 66 + 75 + 84)
                    student_four = 276
                student_five = (82 + 92 + 82 + 70)
                student_five = 326

```
    total scores of each student = [313 329 358 276 326]  

Stuents_record =
\begin{bmatrix}
Students & Total Score \\
Student 1 & 313 \\
Student 2 & 329 \\
Student 3 & 358 \\
Student 4 & 276 \\
Student 5 & 326 \\
\end{bmatrix}

In [9]:
# computing total score for each student by summing across the row.
# rows = students, columns = subjects
total_scores = np.sum(student_scores_2, axis = 1)
print("The total score for each student is: ", total_scores)

The total score for each student is:  [313 329 358 276 326]


 **Average Score per Subject**

- Representing each subject score in an array
```
                student_scores_2 = [
                                [90, 74, 63, 86],
                                [96, 51, 85, 97],
                                [78, 99, 99, 99],
                                [51, 66, 75, 84],
                                [82, 92, 82, 70]
                                ]
```
                math_scores = [90, 96, 78, 51, 82]
                english_scores = [74, 51, 99, 66, 92]
                science_scores = [63, 85, 99, 75, 82]
                agric_scores = [86, 97, 99, 84, 70]
                total_students = 5
```
        math_scores_avg = sum of math_scores / total_students
                                = (90 + 96 + 78 + 51 + 82) / 5
                                                = 397 / 5
                                                = 79.4
                                math_scores_avg = 79.4                          

```
        english_scores_avg = sum of english_scores / total_students
                                = (74 + 51 + 99 + 66 + 92) / 5
                                                = 382 / 5
                                                = 76.4
                                english_scores_avg = 76.4

```
        science_scores_avg = sum of science_scores / total_students
                                = (63 + 85 + 99 + 75 + 82) / 5
                                                = 404 / 5
                                                = 80.8
                                science_scores_avg = 80.8 
```
        agric_scores_avg = sum of agric_scores / total_students
                                = (86 + 97 + 99 + 84 + 70) / 5
                                                = 436 / 5
                                                = 87.2
                                agric_scores_avg = 87.2     
```
Average scores of each student = [79.4  76.4  80.8 87.2]   
```
Average Scores =
\begin{bmatrix}
Subjects & Average Score \\
Mathematics & 79.4 \\
English & 76.4 \\
Science & 80.8 \\
Agric  & 87.2 \\
\end{bmatrix}


In [10]:
# representing all students subject score in an array
math_scores = np.array(student_scores_2[:,0])
english_scores = np.array(student_scores_2[:,1])
science_scores = np.array(student_scores_2[:,2])
agric_scores = np.array(student_scores_2[:,3])

# calculating the average of the students scores in each subject
math_scores_avg = np.mean(math_scores, axis=0)
english_scores_avg = np.mean(english_scores, axis=0)
science_scores_avg = np.mean(science_scores, axis=0)
agric_scores_avg = np.mean(agric_scores, axis=0)

print("The Average of all the Student scores in Mathematics is: ", math_scores_avg)
print("The Average of all the Student scores in English is: ", english_scores_avg)
print("The Average of all the Student scores in Science is: ", science_scores_avg)
print("The Average of all the Student scores in Science is: ", agric_scores_avg)

The Average of all the Student scores in Mathematics is:  79.4
The Average of all the Student scores in English is:  76.4
The Average of all the Student scores in Science is:  80.8
The Average of all the Student scores in Science is:  83.8


**Applying Weights (Scalar Multiplication):**
Science is 3 times more important than others

- Representing all students science score in an array
```
    science_scores = [63, 85, 99, 75, 82]
```
- Science is thrice as important as others, `scalar m = 3`   

- Scalar multiplication to apply weight on the science subject:
   ```
     weighted_science_score = 2(science_scores)
     3(science_scores) => 3([63, 85, 99, 75, 82])
                        [(3 x 63), (3 X 85), (3 X 99), (3 X 75), (3 X 82)]
                        [160  120 225 246]

    weighted_science_score = [160  120 225 246]


In [11]:

student_scores_2 = np.array([
       [90, 74, 63, 86],
       [96, 51, 85, 97],
       [78, 99, 99, 82],
       [51, 66, 75, 84],
       [82, 92, 82, 70]])
# scalar value
scalar_m = 3
# applying scalar multiplication
weighted_science_score = scalar_m * science_scores

print("The weighted science score for each student is:\n ", weighted_science_score)
new_score= np.array([
                            [90, 74, weighted_science_score[0], 86],
                            [96, 51, weighted_science_score[1], 97],
                            [78, 99, weighted_science_score[2],82],
                            [51, 66, weighted_science_score[3], 84],
                            [82, 92, weighted_science_score[4], 70]])

print("The New Total Score for each student is:\n", new_score)

The weighted science score for each student is:
  [189 255 297 225 246]
The New Total Score for each student is:
 [[ 90  74 189  86]
 [ 96  51 255  97]
 [ 78  99 297  82]
 [ 51  66 225  84]
 [ 82  92 246  70]]


   **Total Score after Applying Weights (Scalar Multiplication) on Science Scores**             
- Total score for each student by summing across the row vector.
```
       - new_student_scores_2 = [
                            [90, 74, 189, 86],
                            [96, 51, 255, 97],
                            [78, 99, 297, 82],
                            [51, 66, 225, 84],
                            [82, 92, 246, 70]
                            ]

        - Total score for each student:
                student_one = (90 + 74 + 189 + 86)
                    student_one = 439
                student_two = (96 + 51 + 255 + 97)
                    student_two = 499
                student_three = (78 + 99 + 297 + 82)
                    student_three = 573
                student_four = (51 + 66 + 225 + 84)
                    student_four = 426
                student_five = (82 + 92 + 246 + 70)
                student_five = 490

```
    new total scores of each student = [439 499 573 426 490] 

New Students Record =
\begin{bmatrix}
Students & Total Score \\
Student 1 & 439 \\
Student 2 & 499 \\
Student 3 & 573 \\
Student 4 & 426 \\
Student 5 & 490 \\
\end{bmatrix}

In [12]:
# resetting the array after applying weight on science subject
new_student_scores_2 = np.array([
                            [90, 74, 189, 86],
                            [96, 51, 255, 97],
                            [78, 99, 297, 99],
                            [51, 66, 225, 84],
                            [82, 92, 246, 70]
                            ])
# the total score
new_total_score = np.sum(new_student_scores_2, axis = 1)
print("The total score for each student is: ", new_total_score)

The total score for each student is:  [439 499 573 426 490]


## **3.5 Final Grades Using Matrix Multiplication**

- Representing each subject score in an array
  student_scores_2 = [
                                [90, 74, 63, 86],
                                [96, 51, 85, 97],
                                [78, 99, 99, 82],
                                [51, 66, 75, 84],
                                [82, 92, 82, 70]
                                ]
  student_scores_2(5 X 4)

```
        weight_vector = [ 30% = 0.3 = maths,
                          20% = 0.2 = english,
                          40% = 0.4 = science,
                          10% = 0.1 = agric,
                        ]
       weight_vector(4 X 1)
```
 - final_grade(5 X 1) = (student_scores X weight_vector)
                         
                          student_1_grade = [(90 X 0.3), (74 x 0.2),  (63 X 0.4), (86 X 0.1)]
                          student_2_grade = [(96 X 0.3), (51 x 0.2),  (85 X 0.4), (97 X 0.1)]
                          student_3_grade = [(78 X 0.3), (99 x 0.2),  (99 X 0.4), (82 X 0.1)]
                          student_4_grade = [(51 X 0.3), (66 x 0.2),  (75 X 0.4), (84 X 0.1)]
                          student_5_grade = [(82 X 0.3), (92 x 0.2),  (82 X 0.4), (70 X 0.1)]
 - final_grade

                          student_1_grade =   [27.  14.8 25.2  8.6]
                          student_2_grade =   [28.8 10.2 34.   9.7]
                          student_3_grade =   [23.4 19.8 39.6  8.2]
                          student_4_grade =   [15.3 13.2 30.   8.4]
                          student_5_grade =   [24.6 18.4 32.8  7. ]

  - Total final grade for each student:
  ```
                          student_1_final = (27. + 14.8 + 25.2 +  8.6)
                              student_1_final = 75.6 %

                          student_2_final = (28.8 + 10.2 + 34. + 9.7)
                              student_2_final = 82.7 %

                          student_3_final = (23.4  + 9.8 + 39.6 + 8.2)
                              student_3_final = 91.6%

                         student_4_final = (15.3 + 13.2 + 30. +  8.4)
                              student_4_final = 66.9%

                          student_5_final = (24.6 + 18.4 + 32.8 + 7. )
                              student_5_final = 82.8%

```
```
- Grades
    - A = 75 - 100
    - B = 65 - 74
    - C = 64 - 55
    - D = 54 - 45
    - E = 44 - 40
    - F = 39 - 0

Student Performance =
\begin{bmatrix}
Students & Scores &Grades\\
Student_1 & 75.6% & A\\
Student_2 & 82.7% & A\\
Student_3 & 91.6 & A\\
Student_4 & 66.9% & B\\
Student_4 & 82.8% & A\\
\end{bmatrix}                   
                        

In [13]:
# representing all subject weight vector in an array
weight_vector = [0.3, 0.2, 0.4, 0.1]

student_1 = np.array(student_scores_2[0, :])
student_2= np.array(student_scores_2[1, :])
student_3 = np.array(student_scores_2[2, :])
student_4 = np.array(student_scores_2[3, :])
student_5 = np.array(student_scores_2[4, :])

# calculating the sum of the students scores in each subject
student_1_final = np.sum(student_1 * weight_vector)
student_2_final= np.sum(student_2 * weight_vector)
student_3_final = np.sum(student_3 * weight_vector)
student_4_final = np.sum(student_4 * weight_vector)
student_5_final = np.sum(student_5 * weight_vector)

# adding the final grade for each student
print("Student 1 Final Grade is: ", student_1_final ,"%")
print("Student 2 Final Grade is: ", student_2_final,"%")
print("Student 3 Final Grade is: ", student_3_final,"%")
print("Student 4 Final Grade is: ", student_4_final,"%")
print("Student 5 Final Grade is: ", student_5_final,"%")

student_1_score = student_1 * weight_vector
student_2_score= student_2 * weight_vector
student_3_score = student_3 * weight_vector
student_4_score = student_4 * weight_vector
student_5_score = student_5 * weight_vector
# adding the final grade for each student
print("Student 1 Final Grade is: ", student_1_score ,"%")
print("Student 2 Final Grade is: ", student_2_score,"%")
print("Student 3 Final Grade is: ", student_3_score,"%")
print("Student 4 Final Grade is: ", student_4_score,"%")
print("Student 5 Final Grade is: ", student_5_score,"%")




Student 1 Final Grade is:  75.6 %
Student 2 Final Grade is:  82.7 %
Student 3 Final Grade is:  91.00000000000001 %
Student 4 Final Grade is:  66.9 %
Student 5 Final Grade is:  82.80000000000001 %
Student 1 Final Grade is:  [27.  14.8 25.2  8.6] %
Student 2 Final Grade is:  [28.8 10.2 34.   9.7] %
Student 3 Final Grade is:  [23.4 19.8 39.6  8.2] %
Student 4 Final Grade is:  [15.3 13.2 30.   8.4] %
Student 5 Final Grade is:  [24.6 18.4 32.8  7. ] %


## **Comparing Students (Vector Subtraction)**

- comparing Student 3 and Student 3 performnances by subtracting their score vectors
  - Total final grade for each student:
  ```
                           student_3_final = (23.4  + 9.8 + 39.6 + 8.2)
                              student_3_final = 91.6%

                         student_4_final = (15.3 + 13.2 + 30. +  8.4)
                              student_4_final = 66.9%
- Student performance comparison by subtracting their score vector:
```
                        performance_comparison = -student_4_final + student_3_final
                                               =  -66.9 + 91.6
                                               =   24.1% 
```  
- The difference between the performance of Students 4 and Student 3 is 24.1%, Hence; Student 3 performed better                                                       
                         

In [14]:
# Student performance comparison by subtracting their score vector:
performance_comparison = (- student_4_final) + student_3_final 
performance_comparison
print("The difference between the performance of Students 4 and Student 3 is: ", performance_comparison,"%", "hence; student 3 performed better")

The difference between the performance of Students 4 and Student 3 is:  24.10000000000001 % hence; student 3 performed better
